import type { Metadata } from 'next';
import './globals.scss';
import { Montserrat } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { ptBR } from '@clerk/localizations';

const montserrat = Montserrat({
  weight: ['500', '400', '300'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Pro Spot',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-BR" className="dark">
        <body className={`${montserrat.className} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
